language: "node_js"
node_js:
  - "6.2.0"

before_script:
  - "node app/server.js &"

script: "YOURPACKAGE_COVERAGE=1 ./node_modules/.bin/mocha test -R mocha-lcov-reporter"

after_script: "killall -f node"
